Improve search results
hummingbird-me/kitsu-web pull request #101
Opened 2016-12-21 11:36 UTC by cybrox

This PR componentizes search result items and allow opening them in new tabs. Upon clicking a result, the dropdown will close like normal, however, when opening a result in a new tab, the dropdown will stay, assuming you want to open other entries as well.

- [x] Componentize search results
- [x] Refactor search results to use `href-to`to allow opening them in in new tabs
- [ ] Style new linked search results @JoshFabian 
- [ ] Add additional information to search results  @JoshFabian / @cybrox

2016-12-21 11:46 UTC, trmcnvn requested changes

2016-12-21 11:46 UTC, vevix commented on app/components/application/site-search/group/item.js
> +export default Ember.Component.extend({
`import Component from 'ember-component';`
`export default Component`

2016-12-21 11:46 UTC, vevix commented on app/templates/components/application/site-search/group/item.hbs
> +      {{#if (eq group "users")}}
no context of `group` in new component.

2016-12-21 11:46 UTC, vevix commented on app/templates/components/application/site-search/group/item.hbs
> +      {{#if (eq group "users")}}
Better approach here might be to use `model-type` helper on `item` and see if it `=== user`

2016-12-21 11:46 UTC, vevix commented on app/components/application/site-search/group.js
> +    close() {
✂️ as we aren't doing any additional logic with this action, we can pass it directly to the child component: `close=close`

2016-12-21 11:46 UTC, vevix commented on app/components/application/site-search/group/item.js
> +  link: computed('item', {
Might need to verify this, but I don't think that `item` would ever be recomputed so should switch to a `getter` here.

2016-12-21 11:46 UTC, vevix commented on app/components/application/site-search/group/item.js
> +      get(this, 'router.router').transitionTo(link);
No need to access router directly, the service provides a proxy function: `get(this, 'router').transitionTo(...)`

2016-12-21 11:48 UTC, cybrox commented on app/components/application/site-search/group/item.js
> +export default Ember.Component.extend({
Hrm, I should stop using ember generators for... like everything :|

2016-12-21 11:53 UTC, cybrox commented on app/components/application/site-search/group/item.js
> +      get(this, 'router.router').transitionTo(link);
As far as I know, the proxy function only works when you provide a route + model. In this case, `link` is a string generated by `href-to`. Correct me if I'm wrong?

2016-12-21 11:57 UTC, trmcnvn commented on app/components/application/site-search/group/item.js
> +      get(this, 'router.router').transitionTo(link);
:+1:

2016-12-21 12:07 UTC, trmcnvn approved these changes

2017-01-13 03:37 UTC, vevix commented
Hey @cybrox, I had to rework the way search works for our new trending page at #140. It shouldn't be much work to get these changes transferred over to the new setup, but I expect those changes to be merged before this is finished.

Basically, I've separated the results popover into a new component called `search-results` which both the header & new trending page invoke.

2017-01-13 15:02 UTC, cybrox commented
Sure, I'll put it on my to-do list for the weekend. Shouldn't be much work to just move that around.

cc. @JoshFabian  Could you tell me what (if any) additional elements you'd prefer to be displayed in search results? Then I'm gonna hook them up while I'm at it and you can slap some style on everything to finish it off.

2017-01-17 14:53 UTC, vevix commented
@cybrox Trending branch has been merged, so you're free to update to the latest changes when you're free. ❤️

2017-10-16 23:22 UTC, closed without merging