add airing status to library entries
hummingbird-me/kitsu-web pull request #228
Opened 2017-03-18 21:02 UTC by matthewdias

Changes proposed in this pull request:

add airing status tags to library entries

TODO: styles

2017-03-18 21:03 UTC, matthewdias commented on app/components/users/library/library-entry.js
> +  airingStatus: computed('media.{startDate,endDate,unitCount}', function() {
@vevix is there a place we can put this method so that both `media-information` and `library-entry` components can share it?

2017-03-19 02:18 UTC, trmcnvn requested changes
:heart:

2017-03-19 02:18 UTC, vevix commented on app/templates/components/users/library/library-entry.hbs
> +      </div>
Could you move this up to be a child of `entry-indicators`.

2017-03-19 02:18 UTC, vevix commented on app/components/users/library/library-entry.js
> +  airingStatus: computed('media.{startDate,endDate,unitCount}', function() {
We can move it to `models/media.js` with some minor changes.

```javascript
/**
 * Returns the translation key for the current airing status of this media.
 *
 * @returns {string} Translation Key
 */
airingStatus: computed('{startDate,endDate,unitCount}', function() {
  const start = get(this, 'startDate');
  const end = get(this, 'endDate');
  if (start && (start.isBefore() || start.isSame())) {
    const isOneDay = get(this, 'unitCount') === 1;
    const isPastDay = end && (end.isBefore() || end.isSame());
    return (isOneDay || isPastDay) ? 'finished' : 'current';
  }
  return 'nya';
}).readOnly()
```

I'm not sure `{..,..}` will work without a context, If it doesn't change it to:

`computed('startDate', 'endDate', 'unitCount', ...`

2017-03-19 03:11 UTC, matthewdias commented on app/templates/components/users/library/library-entry.hbs
> +      </div>
ah, thats what that was for

2017-03-19 06:04 UTC, matthewdias commented
hold off on this, i still need to implement `Upcoming`, but ran into some issues so I just pushed what I had for now.

2017-03-20 01:44 UTC, matthewdias commented
@vevix should be good to go now.

2017-03-20 05:37 UTC, vevix commented on app/models/media.js
> +  }).readOnly(),
What's the reasoning behind moving these here? It seems they are only used in the single place.

2017-03-20 07:01 UTC, matthewdias commented on app/models/media.js
> +  }).readOnly(),
ah whoops i was initially going to calculate upcoming based on season, and forgot to move them back when i switched. will do that shortly.

2017-03-20 08:13 UTC, trmcnvn requested changes
:+1: Will merge after final changes.

2017-03-20 08:13 UTC, vevix commented on app/templates/components/media/media-information.hbs
> +          {{capitalize media.season}} {{media.seasonYear}}
`media` context needs to be removed here.

2017-03-20 19:24 UTC, matthewdias commented on app/templates/components/media/media-information.hbs
> +          {{capitalize media.season}} {{media.seasonYear}}
done 😁

2017-03-20 21:26 UTC, matthewdias commented
@vevix all ready 😄

2017-03-21 01:51 UTC, trmcnvn approved these changes

2017-03-21 01:51 UTC, merged