Spoiled unit dropdown
hummingbird-me/kitsu-web pull request #275
Opened 2017-04-08 05:40 UTC by matthewdias

https://kitsu.io/feedback/feature-requests/p/choosing-which-episodechapter-the-spoiler-is-for-or-for-entire-series

- [x] load episodes and spoiled unit
- [ ] set spoiler value accordingly
- [ ] edit
- [ ] ui
- [ ] styles

2017-04-08 05:41 UTC, matthewdias commented on app/templates/components/stream-feed/create-post.hbs
> +        {{one-way-select spoiledUnit
Not sure what to use for UI here. A search field might be too much. Maybe just a number input like in the library?

2017-04-08 05:54 UTC, trmcnvn requested changes
I believe there was talk within #development Slack where we mentioned dropping the link to episodes and changing to just a number. /cc @NuckChorris

2017-04-08 05:54 UTC, vevix commented on app/components/stream-feed/create-post.js
> +        [`${type}_id`]: media.id
Use `get` here.

2017-04-08 05:54 UTC, vevix commented on app/models/episode.js
> +  computedTitle: computed('number', 'canonicalTitle', function() {
Since this is only used in a single place, can we move it there so we aren't computing this for every episode we have.

2017-04-08 05:54 UTC, vevix commented on app/templates/components/stream-feed/create-post.hbs
> +        {{one-way-select spoiledUnit
/cc @JoshFabian

2017-04-08 06:40 UTC, matthewdias commented on app/models/episode.js
> +  computedTitle: computed('number', 'canonicalTitle', function() {
I have no idea how to do this, tbh. Any pointers? 😄

2017-04-09 07:11 UTC, vevix commented on app/models/episode.js
> +  computedTitle: computed('number', 'canonicalTitle', function() {
Hmm yeah, tough with how the UI is setup. Can keep it as-is for now.

2017-07-14 23:16 UTC, matthewdias commented
Continued in #403

2017-07-14 23:16 UTC, closed without merging