WIP mal sync updates
hummingbird-me/kitsu-web pull request #280
Opened 2017-04-10 22:04 UTC by matthewdias

- [ ] group by day

2017-04-11 06:41 UTC, matthewdias commented
just needs styles now @JoshFabian

2017-04-11 07:06 UTC, trmcnvn requested changes

2017-04-11 07:06 UTC, trmcnvn commented on app/components/settings/export/export-basicauth.js
> +  }),
`.readOnly()`

2017-04-11 07:06 UTC, trmcnvn commented on app/components/settings/export/export-basicauth.js
> +      token: get(this, 'password'),
Shouldn't this be `token` and not password?

2017-04-11 07:06 UTC, trmcnvn commented on app/components/settings/export/export-basicauth.js
> +      shareTo: false,
Drop the 2 above, they default to false.

2017-04-11 07:06 UTC, trmcnvn commented on app/components/settings/export/export-basicauth.js
> +        .then(() => invokeAction(this, 'close'))
Wrap in blocks `() => { ... }`

2017-04-11 07:06 UTC, trmcnvn commented on app/components/settings/export/export-select.js
> +  hasExporterFor() {
Let's remove this function.

2017-04-11 07:06 UTC, trmcnvn commented on app/components/settings/export/export-select.js
> +    return this.hasExporterFor('MyAnimeList');
Change this to:

```javascript
hasExporterForMal: computed(function() {
  return !!get(this, 'store').peekAll('linked-account').findBy('kind', 'my-anime-list');
}).readOnly()
```

2017-04-11 07:06 UTC, trmcnvn commented on app/controllers/settings/exports.js
> +import Controller from 'ember-controller';
I don't think this file is needed.

2017-04-11 07:06 UTC, trmcnvn commented on app/models/library-entry-log.js
> +  normalizedRating: computed('rating', function() {
Do we use the `rating` field directly? If not, we can change it to `attr('rating')` to automatically do `rating / 2` on deserialization.

2017-04-11 07:06 UTC, trmcnvn commented on app/models/library-entry-log.js
> +  date: computed('createdAt', function() {
Let's keep display logic out of the model. Move this to the component it's related to.

2017-04-11 07:06 UTC, trmcnvn commented on app/models/library-entry-log.js
> +  linkedAccount: belongsTo('linkedAccount'),
`linked-account`

2017-04-11 07:06 UTC, trmcnvn commented on app/models/linked-account.js
> +
:scissors:

2017-04-11 07:06 UTC, trmcnvn commented on app/models/linked-account.js
> +  libraryEntryLogs: hasMany('libraryEntryLog'),
Blank line between model groups

```
attrs

relationships

computed properties
```

2017-04-11 07:06 UTC, vevix commented on app/models/linked-account.js
> +  sortedLogs: computed('libraryEntryLogs', function() {
Move to component over model. Models should really only contain data unless it's consumed in a lot of places over different components.

2017-04-11 07:06 UTC, vevix commented on app/models/linked-account.js
> +  logsByDate: groupBy('sortedLogs', 'date'),
Same as above.

2017-04-11 07:06 UTC, vevix commented on app/routes/settings/exports.js
> +});
Take a look at the imports route. The pagination code has changed and this code will need to be updated to support that.

2017-04-11 07:06 UTC, vevix commented on package.json
> +    "ember-group-by": "0.0.3",
yarn.lock will need to be updated as well. `yarn install`

2017-04-11 07:06 UTC, vevix commented on app/templates/settings/exports.hbs
> +          </button>
tab here.

2017-04-11 10:29 UTC, trmcnvn requested changes

2017-04-11 10:29 UTC, vevix commented on app/routes/settings/exports.js
> +      include: 'libraryEntryLogs.media'
Let's use fieldsets here since we're bringing in media. http://jsonapi.org/format/#fetching-sparse-fieldsets

2017-04-11 10:29 UTC, vevix commented on app/templates/settings/exports.hbs
> +          {{#if hasNextPage}}
Let's move this conditional up one line so we don't insert an empty div.

2017-04-14 21:25 UTC, matthewdias commented
moved to #285

2017-04-14 21:25 UTC, closed without merging