Edit library list titles and posters
hummingbird-me/kitsu-web pull request #359
Opened 2017-06-01 16:49 UTC by dulleh

Probably should have someone else test these too ^^
Before:
![image](https://cloud.githubusercontent.com/assets/10089976/26690683/2381ea80-46f2-11e7-9ede-4f3c93ebec02.png)
After:
![image](https://cloud.githubusercontent.com/assets/10089976/26690735/569e2cd0-46f2-11e7-9789-f0618bd27891.png)
cc @JoshFabian

2017-06-01 16:51 UTC, matthewdias commented
checkboxes are still off center?

2017-06-01 18:37 UTC, dulleh commented
@matthewdias Checkboxes are off because of the 0.75rem padding on .table .td as it isn't applied to them. I'm not sure how to fix that without breaking the other columns.

2017-06-01 18:45 UTC, matthewdias commented
@dulleh change https://github.com/hummingbird-me/hummingbird-client/blob/the-future/app/styles/pages/_library.scss#L471 to read `padding: 0.75rem 8px;` and then adjust the `line-height` until it looks right.

2017-06-01 19:04 UTC, dulleh commented
![image](https://cloud.githubusercontent.com/assets/10089976/26696205/7972d4fa-4705-11e7-87cf-9392b506c084.png)
@matthewdias works 👌

2017-06-02 08:21 UTC, trmcnvn requested changes

2017-06-02 08:21 UTC, vevix commented on app/styles/components/_ratings.scss
> -
This change breaks the rating widget on other parts of the site. This needs to be reversed and instead remove the margin on the library page only.

2017-07-04 14:17 UTC, dulleh commented
I've just reverted for now because I don't know how to fix it without breaking other things (and don't have a local env. to test).

2017-07-04 14:28 UTC, trmcnvn approved these changes

2017-07-05 01:51 UTC, merged