Feature/unit feeds
hummingbird-me/kitsu-web pull request #403
Opened 2017-07-14 23:15 UTC by matthewdias

![](https://my.mixtape.moe/plwqxr.png)

2017-07-14 23:16 UTC, JoshFabian commented
It's a little ugly - but I'll take over on clean-up when you're finished! 👍

2017-07-14 23:18 UTC, matthewdias commented
ah i forgot i need to add a unit indicator for created posts. will do that shortly.

2017-07-19 06:51 UTC, trmcnvn requested changes

2017-07-19 06:51 UTC, trmcnvn commented on app/components/stream-feed/list.js
> +      } else filter = { manga_id: get(media, 'id'), number };
Let's wrap this in brackets.

2017-07-19 06:51 UTC, trmcnvn commented on app/models/chapter.js
> +  manga: belongsTo('manga'),
`,` :scissors:

2017-07-19 06:51 UTC, trmcnvn commented on app/router.js
> +          this.route('index', { path: '/' });
Pretty sure this can be omitted.

2017-07-19 06:51 UTC, vevix commented on app/templates/media/show/units/index.hbs
> +{{ad-unit unit="kitsu.media.units.top"
Just keep this as `episodes` -- It's actually pulling a specific unit.

2017-07-20 06:20 UTC, vevix commented
@JoshFabian Can you design in the branch here?

@matthewdias Conflicts :sob:

2017-07-20 23:29 UTC, merged