reaction actions
hummingbird-me/kitsu-web pull request #404
Opened 2017-07-16 07:23 UTC by matthewdias

I don't know how this affects activities.

_"Every action has an equal and opposite reaction..."_

2017-07-16 08:16 UTC, vevix commented on app/templates/media-reactions.hbs
> +  {{media/media-reaction reaction=model}}
Shouldn't we use the feed component for the permalink page?

2017-07-16 08:16 UTC, vevix commented on app/components/media/media-reaction.js
> +    if (get(this, 'session.account').hasRole('admin', get(this, 'reaction'))) {
We should check if the user is the owner here too.

2017-07-19 05:16 UTC, trmcnvn requested changes

2017-07-19 05:16 UTC, vevix commented on app/components/media/media-reaction.js
> +  canDelete: getter(function() {
getter -> computed.

2017-07-19 05:16 UTC, vevix commented on app/components/media/media-reaction.js
> +  host: getter(() => `${location.protocol}//${location.host}`),
Don't want to continue the use of `getter`, we can just set this in `init`

2017-07-19 05:22 UTC, vevix commented
So many conflicts :scream:

2017-07-19 05:23 UTC, matthewdias commented
oh my god what happened

2017-07-19 08:25 UTC, trmcnvn approved these changes

2017-07-19 08:26 UTC, vevix commented
More conflicts :P

2017-07-19 08:55 UTC, merged