Replace position: sticky with sticky-js
hummingbird-me/kitsu-web pull request #408
Opened 2017-07-18 20:42 UTC by matthewdias

2017-07-18 20:47 UTC, trmcnvn requested changes

2017-07-18 20:47 UTC, vevix commented on app/components/explore/category-sidebar/general-categories.js
> +    this.sticky = new Sticky('.is-sticky');
I feel like these should be done in the `didInsertComponent` hook, rather than initialization of the Component module.

2017-07-18 20:47 UTC, vevix commented on app/controllers/dashboard.js
> +    this.sticky = new Sticky('.is-sticky');
Since we don't have a post-insert hook available in Controllers, this should be wrapped in an `afterRender` schedule.

2017-07-18 21:27 UTC, matthewdias commented on app/templates/media/show.hbs
> +  <div class="is-sticky media-sidebar--sticky" data-margin-top="260">
I have no idea why but this sticky doesn't work consistently, while the rest do. Maybe has to do with the weird positioning we're doing on it?

2017-07-18 21:36 UTC, NuckChorris commented
Why even bother?  Support for `position: sticky` is [already pretty good](http://caniuse.com/#feat=css-sticky) and it only gets better *plus* it can degrade gracefully.  Isn't this just another library to slow page loads?

2017-07-18 21:41 UTC, matthewdias commented
`position: sticky` doesn't account for viewport heights. This library will disable the sticky when the window is small, so we don't get any cutoff elements. People have been complaining about it a lot.

2017-07-18 21:41 UTC, NuckChorris commented
Ah, okay, that's good then :+1:

2017-07-18 21:44 UTC, wopian commented
Alternatively use a media query to not `position: sticky` if viewport height is too small

2017-07-19 08:57 UTC, vevix commented
This will need some changes after media page I think.

2017-07-20 06:20 UTC, vevix commented
:D @matthewdias Can you update for media pages? :heart:

2017-07-20 09:31 UTC, merged