Add viewing and creating uploads
hummingbird-me/kitsu-web pull request #459
Opened 2017-09-13 09:07 UTC by matthewdias

🌆  ⬆️

2018-02-03 04:43 UTC, NuckChorris commented
Just rebased this, @vevix @matthewdias do either of you remember what still needed done?

2018-02-03 04:58 UTC, matthewdias commented
iirc it was finished unless there are some new bugs or requirements

2018-02-07 05:16 UTC, trmcnvn requested changes

2018-02-07 05:16 UTC, trmcnvn commented on app/components/stream-feed/create-post.js
> +  uploads: [],
Move this initialization to `init`

2018-02-07 05:16 UTC, trmcnvn commented on app/components/stream-feed/create-post.js
> +  uploads: [],
Ref: https://poteto.github.io/component-best-practices/#/leaky

2018-02-07 05:16 UTC, trmcnvn commented on app/components/stream-feed/create-post.js
> +      set(queue, 'files', A());
Capture this exception with Raven

2018-02-07 05:16 UTC, trmcnvn commented on app/components/stream-feed/create-post.js
> +    },
Strip `,`

2018-02-07 05:16 UTC, trmcnvn commented on app/components/stream-feed/items/post.js
> +  uploads: [],
Same as above comment regarding Object/Array init on components.

2018-02-07 05:16 UTC, trmcnvn commented on app/components/stream-feed/items/post.js
> +        ownerType: 'Post'
We are sure this doesn't expect lowercase?

2018-02-07 05:16 UTC, vevix commented on app/components/stream-feed/items/post/comment-box.js
> +import { A } from 'ember-array/utils';
Update these to use new module imports.

2018-02-07 05:16 UTC, vevix commented on app/components/stream-feed/items/post/comment-box.js
> +      set(queue, 'files', A());
Same as above: Capture with Raven and can we use `[]`.

2018-02-07 05:16 UTC, vevix commented on app/components/stream-feed/items/post/comment-box.js
> +    },
✂️ `,`

2018-02-07 05:16 UTC, vevix commented on app/components/stream-feed/items/post/comment.js
> +  galleryItems: [],
👉 `init`

2018-02-07 05:16 UTC, vevix commented on app/components/stream-feed/items/post/uploads-grid.js
> +import computed from 'ember-computed';
Update to new module imports.

2018-02-07 05:16 UTC, vevix commented on app/components/stream-feed/items/post/uploads-grid.js
> +};
I'm okay with leaving this here, but it's probably best to extract to a util.

2018-02-07 05:16 UTC, vevix commented on app/components/stream-feed/items/post/uploads-grid.js
> +  galleryItems: [],
👉 `init`

2018-02-07 05:16 UTC, vevix commented on app/serializers/comment.js
> +    uploads: { serialize: true }
Is this needed at all? Should serialize all except ones explicitly defined not to.

2018-02-07 05:16 UTC, vevix commented on app/serializers/post.js
> +    uploads: { serialize: true }
⬆️

2018-02-07 05:16 UTC, vevix commented on app/components/stream-feed/create-post.js
> +      set(queue, 'files', A());
Can we just `[]` here instead of Ember.Array?

2018-06-22 18:42 UTC, trmcnvn approved these changes

2018-06-26 14:55 UTC, merged