Better notifications
hummingbird-me/kitsu-web pull request #80
Opened 2016-12-06 16:39 UTC by cybrox

- Will mark notifications as read when they are clicked
- Will reload posts on when they are open on the permalink page
- Add Mixin for embers new `getOwner` hack

cc @vevix

2016-12-06 19:41 UTC, cybrox commented on app/mixins/get-owner.js
> + * Simple mixing for using getOwner
_"mixing"_, yep, I need more sleep 💣

2016-12-06 23:10 UTC, trmcnvn requested changes
This approach has a few issues.

First, if the comment referenced in the notification is past the fold (not the 2 most recent), then reloading the comments isn't going to show that content anyway.

Second, if it's a brand new comment then implementing realtime of comments would negate the need for this.

------

I think the better approach here is to drop the hacks and keep the mark as read code. Eventually direct comment linking (via hash or query param) & realtime will fix both issues here.

2016-12-06 23:10 UTC, trmcnvn commented on app/components/application/user-notifications/item.js
> +      this.sendAction('followNotification', get(this, 'group'), get(this, 'target'));
`invokeAction(this, ...)`

2016-12-06 23:10 UTC, trmcnvn commented on app/mixins/get-owner.js
> +const { getOwner } = Ember;
`import ... from ember-owner/get`

2016-12-06 23:10 UTC, trmcnvn commented on app/components/stream-feed/items/post/comments.js
> +    }).catch(() => {});
Logic should be moved to a function or the task itself as it's now duplicated.

2016-12-06 23:10 UTC, trmcnvn commented on app/mixins/get-owner.js
> +export default Ember.Mixin.create({
`import ... from 'ember-metal/mixin'`

2016-12-07 15:34 UTC, cybrox commented
Dropped the hacks, mark as read, then transition with injected router.

2016-12-07 21:39 UTC, trmcnvn approved these changes

2016-12-07 21:39 UTC, merged